string $selection_list[] = `ls -sl`;

for( $object in $selection_list )
{
   int $result_list[] = ` polyEvaluate -f $object`;
   
   if( $result_list[0]<3 )
    {
        int $probability = rand(1 , 3);
        print($probability );
        if($probability ==1)
            sets -e -forceElement SG_joung $object;
           else
            sets -e -forceElement SG_old $object;
    }
    else
    {
        sets -e -forceElement SG_trunk $object;
     }
    
}